services:
  postgres:
    image: postgres:16-alpine
    container_name: posto-postgres
    environment:
      POSTGRES_DB: posto_abastecimento
      POSTGRES_USER: posto
      POSTGRES_PASSWORD: posto
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
