spring.application.name=abastecimento

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/posto_abastecimento}
spring.datasource.username=${DB_USER:posto}
spring.datasource.password=${DB_PASSWORD:posto}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true

springdoc.swagger-ui.path=/swagger-ui.html
